
#line 2 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer bx_create_buffer
#define yy_delete_buffer bx_delete_buffer
#define yy_scan_buffer bx_scan_buffer
#define yy_scan_string bx_scan_string
#define yy_scan_bytes bx_scan_bytes
#define yy_init_buffer bx_init_buffer
#define yy_flush_buffer bx_flush_buffer
#define yy_load_buffer_state bx_load_buffer_state
#define yy_switch_to_buffer bx_switch_to_buffer
#define yypush_buffer_state bxpush_buffer_state
#define yypop_buffer_state bxpop_buffer_state
#define yyensure_buffer_stack bxensure_buffer_stack
#define yy_flex_debug bx_flex_debug
#define yyin bxin
#define yyleng bxleng
#define yylex bxlex
#define yylineno bxlineno
#define yyout bxout
#define yyrestart bxrestart
#define yytext bxtext
#define yywrap bxwrap
#define yyalloc bxalloc
#define yyrealloc bxrealloc
#define yyfree bxfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define bx_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer bx_create_buffer
#endif

#ifdef yy_delete_buffer
#define bx_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer bx_delete_buffer
#endif

#ifdef yy_scan_buffer
#define bx_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer bx_scan_buffer
#endif

#ifdef yy_scan_string
#define bx_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string bx_scan_string
#endif

#ifdef yy_scan_bytes
#define bx_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes bx_scan_bytes
#endif

#ifdef yy_init_buffer
#define bx_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer bx_init_buffer
#endif

#ifdef yy_flush_buffer
#define bx_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer bx_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define bx_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state bx_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define bx_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer bx_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define bxpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state bxpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define bxpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state bxpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define bxensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack bxensure_buffer_stack
#endif

#ifdef yylex
#define bxlex_ALREADY_DEFINED
#else
#define yylex bxlex
#endif

#ifdef yyrestart
#define bxrestart_ALREADY_DEFINED
#else
#define yyrestart bxrestart
#endif

#ifdef yylex_init
#define bxlex_init_ALREADY_DEFINED
#else
#define yylex_init bxlex_init
#endif

#ifdef yylex_init_extra
#define bxlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra bxlex_init_extra
#endif

#ifdef yylex_destroy
#define bxlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy bxlex_destroy
#endif

#ifdef yyget_debug
#define bxget_debug_ALREADY_DEFINED
#else
#define yyget_debug bxget_debug
#endif

#ifdef yyset_debug
#define bxset_debug_ALREADY_DEFINED
#else
#define yyset_debug bxset_debug
#endif

#ifdef yyget_extra
#define bxget_extra_ALREADY_DEFINED
#else
#define yyget_extra bxget_extra
#endif

#ifdef yyset_extra
#define bxset_extra_ALREADY_DEFINED
#else
#define yyset_extra bxset_extra
#endif

#ifdef yyget_in
#define bxget_in_ALREADY_DEFINED
#else
#define yyget_in bxget_in
#endif

#ifdef yyset_in
#define bxset_in_ALREADY_DEFINED
#else
#define yyset_in bxset_in
#endif

#ifdef yyget_out
#define bxget_out_ALREADY_DEFINED
#else
#define yyget_out bxget_out
#endif

#ifdef yyset_out
#define bxset_out_ALREADY_DEFINED
#else
#define yyset_out bxset_out
#endif

#ifdef yyget_leng
#define bxget_leng_ALREADY_DEFINED
#else
#define yyget_leng bxget_leng
#endif

#ifdef yyget_text
#define bxget_text_ALREADY_DEFINED
#else
#define yyget_text bxget_text
#endif

#ifdef yyget_lineno
#define bxget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno bxget_lineno
#endif

#ifdef yyset_lineno
#define bxset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno bxset_lineno
#endif

#ifdef yywrap
#define bxwrap_ALREADY_DEFINED
#else
#define yywrap bxwrap
#endif

#ifdef yyalloc
#define bxalloc_ALREADY_DEFINED
#else
#define yyalloc bxalloc
#endif

#ifdef yyrealloc
#define bxrealloc_ALREADY_DEFINED
#else
#define yyrealloc bxrealloc
#endif

#ifdef yyfree
#define bxfree_ALREADY_DEFINED
#else
#define yyfree bxfree
#endif

#ifdef yytext
#define bxtext_ALREADY_DEFINED
#else
#define yytext bxtext
#endif

#ifdef yyleng
#define bxleng_ALREADY_DEFINED
#else
#define yyleng bxleng
#endif

#ifdef yyin
#define bxin_ALREADY_DEFINED
#else
#define yyin bxin
#endif

#ifdef yyout
#define bxout_ALREADY_DEFINED
#else
#define yyout bxout
#endif

#ifdef yy_flex_debug
#define bx_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug bx_flex_debug
#endif

#ifdef yylineno
#define bxlineno_ALREADY_DEFINED
#else
#define yylineno bxlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 227
#define YY_END_OF_BUFFER 228
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[510] =
    {   0,
        0,    0,    0,    0,    0,    0,  228,  225,    1,  223,
      211,  225,  224,  197,  208,  225,  213,  214,  198,  195,
      196,  199,  219,  219,  222,  207,  225,  206,  186,  212,
      221,  210,  103,   19,    6,   48,  221,  221,  221,  185,
      221,  221,  221,  221,   13,  221,   14,   53,   27,   11,
      221,   70,  221,   90,   55,  221,  221,  209,  226,    1,
      226,  222,  226,    1,  203,    0,  216,    0,  224,  220,
        0,  215,    0,  218,  219,    0,  201,  204,  202,  205,
      200,  221,  221,  120,  104,  221,  221,  124,  121,  105,
      130,  221,   86,  125,  221,  122,  106,  221,  221,   22,

      176,  126,  221,  123,  129,  107,  221,  221,   24,  179,
      127,  221,  221,  221,  221,  221,  221,  177,  221,  221,
       30,  180,  221,  221,  181,  221,  221,    9,  221,  172,
      221,  221,  182,   17,  221,  221,  221,  221,  221,  221,
      221,  221,  221,    3,  221,   19,  221,  221,  221,  221,
      221,  164,  165,  221,  221,  221,  221,  221,  221,  221,
      221,   81,  221,  221,  128,  221,  221,  221,  131,  221,
      178,  221,  221,  221,  221,  221,  221,  221,  221,  221,
       16,  221,  221,  221,  221,  221,   56,  221,  221,  192,
      193,  194,  220,  217,  221,  103,   35,   34,  221,   50,

       49,  111,  221,  221,  221,  221,   38,    5,  221,   47,
      221,  221,  221,  109,  221,   65,  221,  221,  140,  146,
      141,  142,  145,  143,  221,  173,  144,  147,  221,  221,
       30,   41,  221,  221,   39,  221,  221,   66,   40,  221,
      221,   42,  221,  221,  190,   37,  221,  221,   68,    4,
      221,  221,  221,  221,  221,  221,  221,  166,  167,  168,
      169,  170,  171,  112,  148,  132,  113,  149,  133,  156,
      163,  157,  158,  161,  159,  221,   28,  221,  221,  174,
       91,  160,  162,   82,    2,  221,  108,  221,  221,   67,
      221,  110,  221,   31,  175,  221,  221,  221,  221,   44,

      221,  221,   69,  221,   43,  221,  221,  221,  221,  221,
      221,  184,   32,   33,  221,  221,  221,  187,  221,    7,
       23,  221,  221,  221,  221,  221,   74,   25,  221,   52,
      221,  221,  185,   21,  221,  221,  221,  221,  221,  221,
       12,  101,  221,  221,  221,  221,  221,   51,  114,  150,
      134,  115,  151,  135,  116,  152,  136,  117,  153,  137,
      118,  154,  138,  119,  155,  139,   89,  221,   28,  221,
      221,  221,  221,   92,   79,  221,  221,   26,   10,   73,
      221,  221,   64,   36,  221,  221,  221,  221,  221,  221,
      221,  221,   15,   18,  221,  221,  221,   61,  221,  221,

      221,  221,  183,  221,  221,  221,   93,   45,  221,  221,
      221,  221,  221,   80,   62,  221,  221,  221,  221,  221,
       97,  221,  221,  221,   75,  221,  221,  221,   87,   99,
       90,  188,  221,  221,   46,   54,  102,   71,   98,  221,
       17,  221,   83,   20,  221,    0,  221,  189,  221,  221,
      221,  191,  221,  221,    0,  221,   16,  221,  221,  221,
      221,  221,   59,   63,    0,  221,   57,  221,   60,    0,
       96,    0,    0,   88,  221,  221,  221,    8,  221,    0,
      221,  221,    0,    0,    0,   84,   58,  221,  221,    0,
        0,   29,  221,    0,   77,   76,  221,   72,    0,    0,

      221,    0,   95,   85,    0,   94,   78,  100,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   13,    1,   14,    1,   15,   16,   17,   18,
       19,   20,   21,   22,   22,   23,   24,    1,   25,   26,
       27,   28,   29,   30,   31,   31,   31,   31,   31,   31,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
        1,   33,    1,   34,   32,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   32,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,    1,   60,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    1,    1,
        4,    5,    1,    1,    4,    6,    6,    6,    4,    4,
        7,    7,    7,    5,    5,    7,    5,    7,    5,    5,
        5,    7,    7,    7,    5,    7,    8,    5,    5,    1
    } ;

static const flex_int16_t yy_base[522] =
    {   0,
        0,    0,   59,   61,   63,   65,  607,  608,  604,  608,
      578,   64,    0,    0,  608,   61,  608,  608,  608,  608,
      608,  608,   48,    0,  608,   55,  577,   64,  608,  608,
        0,  608,   57,   62,   75,   91,  109,   44,   83,  564,
      113,  153,  140,   27,   62,   69,  146,  548,  183,  200,
      144,  554,   41,   87,  108,  554,  553,  608,  608,  596,
      243,  608,    0,  595,  608,  126,  608,    0,    0,    0,
      132,  608,    0,  167,    0,    0,  608,  608,  608,  608,
      608,    0,  558,    0,  550,  537,  536,    0,    0,  549,
      163,  552,    0,    0,  545,    0,  538,  541,  533,   46,

        0,    0,  158,    0,   73,    0,  551,  542,  545,    0,
        0,  526,   49,  525,  120,  536,  531,  107,  536,  543,
      523,    0,  523,  527,    0,  529,  520,    0,  115,    0,
      522,  518,    0,  519,  140,  522,  533,  514,  509,  527,
      507,  520,  522,    0,  520,  509,  512,  515,  514,  141,
      213,  219,  232,  499,  137,  498,  180,  241,  505,  518,
      161,  517,  498,  502,  182,  506,  505,  493,  501,  506,
      166,  177,  501,  497,  233,  497,  505,  505,  487,  482,
      486,  497,  482,  495,  490,  226,    0,  486,  485,    0,
        0,    0,    0,    0,  485,    0,    0,    0,  477,    0,

        0,    0,  493,  490,  480,  472,    0,    0,  483,  484,
      483,  486,  477,    0,  484,    0,  465,  476,    0,    0,
        0,    0,    0,    0,  481,    0,    0,    0,  462,  473,
        0,    0,  477,  463,    0,  463,  457,    0,    0,  470,
      450,    0,  453,  468,    0,    0,  466,  451,    0,    0,
      464,  463,  463,  453,  453,  447,  444,  254,  265,  266,
      269,  270,  273,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  458,  195,  450,  441,    0,
        0,    0,    0,    0,  168,  437,    0,  453,  439,    0,
      439,    0,  448,    0,    0,  439,  438,  433,  449,    0,

      445,  444,    0,  445,    0,  446,  441,  422,  441,  426,
      423,    0,    0,    0,  417,  421,  429,    0,  437,  428,
        0,  417,  429,  431,  430,  414,    0,    0,  424,    0,
      412,  428,    0,    0,  411,  426,  414,  402,  412,  421,
        0,    0,  421,  412,  401,  414,  394,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  399,    0,  392,
      401,  413,  401,    0,    0,  393,  408,    0,    0,    0,
      407,  395,    0,    0,  403,  388,  405,  396,  396,  398,
      397,  382,    0,    0,  393,  386,  393,    0,  389,  391,

      383,  376,    0,  382,  372,  381,    0,    0,  385,  374,
      378,  374,  406,    0,    0,  366,  365,  366,  375,  376,
        0,  375,  371,  367,  397,  373,  365,  355,    0,    0,
      361,    0,  363,  351,    0,    0,    0,    0,    0,  358,
        0,  357,    0,    0,  361,  349,  361,    0,  360,  355,
      351,    0,  382,  343,  227,  352,    0,  357,  353,  350,
      332,  331,    0,    0,  316,  317,    0,  323,    0,  301,
        0,  300,  289,    0,  278,  278,  287,    0,  273,  263,
      267,  282,  269,  270,  274,    0,    0,  264,  259,  257,
      240,    0,  225,  216,  608,  608,  198,    0,  200,  193,

      160,  119,    0,  608,   99,    0,  608,  608,  608,  329,
      337,  345,  350,  358,  364,   97,  370,   76,  376,  382,
      383
    } ;

static const flex_int16_t yy_def[522] =
    {   0,
      509,    1,  510,  510,  510,  510,  509,  509,  509,  509,
      509,  511,  512,  513,  509,  514,  509,  509,  509,  509,
      509,  509,  515,  516,  509,  509,  509,  509,  509,  509,
      517,  509,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  509,  509,  509,
      509,  509,  518,  509,  509,  511,  509,  511,  512,  519,
      514,  509,  514,  515,  516,  520,  509,  509,  509,  509,
      509,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,   61,
      521,  518,  519,  520,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,

      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  509,  517,  517,  517,  517,
      517,  517,  517,  517,  509,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  509,  517,  517,  517,  517,  509,
      517,  509,  509,  517,  517,  517,  517,  517,  517,  509,
      517,  517,  509,  509,  509,  517,  517,  517,  517,  509,
      509,  517,  517,  509,  509,  509,  517,  517,  509,  509,

      517,  509,  517,  509,  509,  517,  509,  509,    0,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509
    } ;

static const flex_int16_t yy_nxt[669] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   24,
       24,   24,   24,   24,   25,   26,   27,   28,   29,   30,
       31,   31,    8,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       60,   10,   60,   10,   60,   10,   60,   10,   67,   72,
       75,   75,  139,   61,  140,   61,  181,   63,  192,   63,
       77,   78,  208,   62,  209,   62,  182,   62,  120,   62,
       80,   81,  121,   73,   83,  122,   68,  220,   84,   75,

      141,   85,   86,   89,   76,  221,   90,  142,  143,   95,
       91,   87,   92,   88,   93,  144,   96,  214,   94,   97,
      123,  183,   98,   99,  215,  100,  101,  124,  184,  103,
       67,  102,  104,  105,  125,  106,  107,  185,  108,  508,
       72,  109,  110,  112,  113,  114,  115,  111,  116,  227,
      127,  117,  128,  186,  236,  228,  187,  507,   68,  129,
      118,  130,  223,  131,   73,  119,  237,  132,  133,  133,
      133,  133,  133,  133,  133,  134,  224,  135,  175,  256,
      145,  146,  136,  257,  147,  271,  176,  137,  177,   75,
       75,  241,  242,  272,  178,  179,  148,  138,  149,  151,

      200,  201,  210,  282,  294,  152,  153,  202,  211,  283,
      212,  506,  213,  372,  295,  296,  373,  154,  155,  156,
      157,  158,  274,  509,  297,  159,  287,  160,  258,  259,
      260,  261,  262,  263,  161,  162,  275,  368,  163,  505,
      288,  164,  165,  504,  166,  167,  369,  168,  169,  503,
      170,  171,  172,  502,  264,  173,  265,  174,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  267,  300,  268,
      312,  294,  472,  501,  266,  276,  301,  473,  191,  191,
      191,  277,  500,  191,  191,  191,  278,  269,  191,  349,
      191,  350,  279,  499,  191,  191,  191,  490,  191,  191,

      352,  355,  353,  356,  358,  361,  359,  362,  364,  351,
      365,  498,  497,  491,  496,  495,  494,  493,  492,  489,
      354,  357,  488,  487,  360,  363,  486,  485,  366,   59,
       59,   59,   59,   59,   59,   59,   59,   66,  484,   66,
       66,   66,   66,   66,   66,   69,  483,   69,   69,   69,
       69,   69,   69,   70,   70,   70,   70,   70,   71,  482,
       71,   71,   71,   71,   71,   71,   74,  481,  480,  479,
      478,   74,   82,   82,   82,   82,   82,   82,  193,  193,
      193,  193,  193,  193,  194,  194,  477,  194,  191,  191,
      191,  476,  475,  474,  471,  470,  469,  468,  467,  466,

      465,  464,  463,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  403,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  371,  370,  367,  348,  347,  346,  345,

      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  299,  298,  293,  292,  291,  290,  289,  286,
      285,  284,  281,  280,  273,  270,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  240,
      239,  238,  235,  234,  233,  232,  231,  230,  229,  226,
      225,  222,  219,  218,  217,  216,  207,  206,  205,  204,
      203,  199,  198,  197,  196,  195,   64,   64,  189,  188,

      180,  150,  126,   79,   65,   64,  509,    7,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509
    } ;

static const flex_int16_t yy_chk[669] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,    5,    5,    6,    6,   12,   16,
       23,   23,   44,    3,   44,    4,   53,    5,  518,    6,
       26,   26,  100,    3,  100,    4,   53,    5,   38,    6,
       28,   28,   38,   16,   33,   38,   12,  113,   33,  516,

       45,   33,   33,   34,   23,  113,   34,   45,   46,   35,
       34,   33,   34,   33,   34,   46,   35,  105,   34,   35,
       39,   54,   35,   35,  105,   35,   35,   39,   54,   36,
       66,   35,   36,   36,   39,   36,   36,   54,   36,  505,
       71,   36,   36,   37,   37,   37,   37,   36,   37,  118,
       41,   37,   41,   55,  129,  118,   55,  502,   66,   41,
       37,   41,  115,   41,   71,   37,  129,   41,   42,   42,
       42,   42,   42,   42,   42,   43,  115,   43,   51,  150,
       47,   47,   43,  150,   47,  155,   51,   43,   51,   74,
       74,  135,  135,  155,   51,   51,   47,   43,   47,   49,

       91,   91,  103,  161,  171,   49,   49,   91,  103,  161,
      103,  501,  103,  285,  171,  172,  285,   49,   49,   49,
       49,   49,  157,   74,  172,   49,  165,   49,  151,  151,
      151,  151,  151,  151,   49,   50,  157,  277,   50,  500,
      165,   50,   50,  499,   50,   50,  277,   50,   50,  497,
       50,   50,   50,  494,  152,   50,  152,   50,   61,   61,
       61,   61,   61,   61,   61,   61,   61,  153,  175,  153,
      186,  186,  455,  493,  152,  158,  175,  455,   61,   61,
       61,  158,  491,   61,   61,   61,  158,  153,   61,  258,
       61,  258,  158,  490,   61,   61,   61,  480,   61,   61,

      259,  260,  259,  260,  261,  262,  261,  262,  263,  258,
      263,  489,  488,  480,  485,  484,  483,  482,  481,  479,
      259,  260,  477,  476,  261,  262,  475,  473,  263,  510,
      510,  510,  510,  510,  510,  510,  510,  511,  472,  511,
      511,  511,  511,  511,  511,  512,  470,  512,  512,  512,
      512,  512,  512,  513,  513,  513,  513,  513,  514,  468,
      514,  514,  514,  514,  514,  514,  515,  466,  465,  462,
      461,  515,  517,  517,  517,  517,  517,  517,  519,  519,
      519,  519,  519,  519,  520,  520,  460,  520,  521,  521,
      521,  459,  458,  456,  454,  453,  451,  450,  449,  447,

      446,  445,  442,  440,  434,  433,  431,  428,  427,  426,
      425,  424,  423,  422,  420,  419,  418,  417,  416,  413,
      412,  411,  410,  409,  406,  405,  404,  402,  401,  400,
      399,  397,  396,  395,  392,  391,  390,  389,  388,  387,
      386,  385,  382,  381,  377,  376,  373,  372,  371,  370,
      368,  347,  346,  345,  344,  343,  340,  339,  338,  337,
      336,  335,  332,  331,  329,  326,  325,  324,  323,  322,
      320,  319,  317,  316,  315,  311,  310,  309,  308,  307,
      306,  304,  302,  301,  299,  298,  297,  296,  293,  291,
      289,  288,  286,  279,  278,  276,  257,  256,  255,  254,

      253,  252,  251,  248,  247,  244,  243,  241,  240,  237,
      236,  234,  233,  230,  229,  225,  218,  217,  215,  213,
      212,  211,  210,  209,  206,  205,  204,  203,  199,  195,
      189,  188,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  174,  173,  170,  169,  168,  167,  166,  164,
      163,  162,  160,  159,  156,  154,  149,  148,  147,  146,
      145,  143,  142,  141,  140,  139,  138,  137,  136,  134,
      132,  131,  127,  126,  124,  123,  121,  120,  119,  117,
      116,  114,  112,  109,  108,  107,   99,   98,   97,   95,
       92,   90,   87,   86,   85,   83,   64,   60,   57,   56,

       52,   48,   40,   27,   11,    9,    7,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "bx_lexer.l"
#line 2 "bx_lexer.l"
/////////////////////////////////////////////////////////////////////////
// $Id$
/////////////////////////////////////////////////////////////////////////

#include <stdlib.h>
#include <string.h>

#ifdef WIN32
	#include <io.h>
	#define YY_NO_UNISTD_H
#endif

#include "debug.h"
#if BX_DEBUGGER

#include "bx_parser.h"

int bx_yyinput(char *buf, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf, ret, max_size) (ret = bx_yyinput(buf, max_size))

static char    *lex_input_ptr = NULL;
static unsigned lex_input_size = 0;

#if BX_SUPPORT_X86_64
  #define LONG_MODE_8BL_REG(reg) \
     { bxlval.uval = reg; return(BX_TOKEN_8BL_REG); }
  #define LONG_MODE_16B_REG(reg) \
     { bxlval.uval = reg; return(BX_TOKEN_16B_REG); }
  #define LONG_MODE_32B_REG(reg) \
     { bxlval.uval = reg; return(BX_TOKEN_32B_REG); }
  #define LONG_MODE_64B_REG(reg) \
     { bxlval.uval = reg; return(BX_TOKEN_64B_REG); }
#else
  #define LONG_MODE_8BL_REG(reg) \
     { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }
  #define LONG_MODE_16B_REG(reg) \
     { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }
  #define LONG_MODE_32B_REG(reg) \
     { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }
  #define LONG_MODE_64B_REG(reg) \
     { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }
#endif

#if BX_SUPPORT_EVEX
  #define EVEX_OPMASK_REG(reg) \
     { bxlval.uval = reg; return(BX_TOKEN_OPMASK_REG); }
#else
  #define EVEX_OPMASK_REG(reg) \
     { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }
#endif

#line 1070 "<stdout>"

#line 1072 "<stdout>"

#define INITIAL 0
#define EXAMINE 1
#define DISASM 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 59 "bx_lexer.l"

#line 1293 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 510 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 608 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "bx_lexer.l"
; // eat up whitespace
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SET); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "bx_lexer.l"
{ bxlval.bval = 1; return(BX_TOKEN_ON); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "bx_lexer.l"
{ bxlval.bval = 0; return(BX_TOKEN_OFF); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CRC); }
	YY_BREAK
case 6:
#line 66 "bx_lexer.l"
case 7:
#line 67 "bx_lexer.l"
case 8:
YY_RULE_SETUP
#line 67 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IF); }
	YY_BREAK
case 10:
#line 70 "bx_lexer.l"
case 11:
YY_RULE_SETUP
#line 70 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STEPN); }
	YY_BREAK
case 12:
#line 72 "bx_lexer.l"
case 13:
#line 73 "bx_lexer.l"
case 14:
YY_RULE_SETUP
#line 73 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STEP_OVER); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LIST_BREAK); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_VBREAKPOINT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LBREAKPOINT); }
	YY_BREAK
case 18:
#line 78 "bx_lexer.l"
case 19:
#line 79 "bx_lexer.l"
case 20:
YY_RULE_SETUP
#line 79 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PBREAKPOINT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INFO); }
	YY_BREAK
case 22:
#line 82 "bx_lexer.l"
case 23:
YY_RULE_SETUP
#line 82 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTROL_REGS); }
	YY_BREAK
case 24:
#line 84 "bx_lexer.l"
case 25:
YY_RULE_SETUP
#line 84 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEBUG_REGS); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SEGMENT_REGS); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_R); }
	YY_BREAK
case 28:
#line 88 "bx_lexer.l"
case 29:
YY_RULE_SETUP
#line 88 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_REGS); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FPU); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_XMM); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_YMM); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ZMM); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_AVX); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_AMX); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_MMX); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CPU); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IDT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IVT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GDT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LDT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TSS); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TAB); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LINUX); }
	YY_BREAK
case 46:
#line 106 "bx_lexer.l"
case 47:
#line 107 "bx_lexer.l"
case 48:
YY_RULE_SETUP
#line 107 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEL_BREAKPOINT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ENABLE_BREAKPOINT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISABLE_BREAKPOINT); }
	YY_BREAK
case 51:
#line 111 "bx_lexer.l"
case 52:
#line 112 "bx_lexer.l"
case 53:
YY_RULE_SETUP
#line 112 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUIT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 113 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DETACH); }
	YY_BREAK
case 55:
#line 115 "bx_lexer.l"
case 56:
YY_RULE_SETUP
#line 115 "bx_lexer.l"
{ BEGIN(EXAMINE); bxlval.sval = strdup(bxtext); return(BX_TOKEN_EXAMINE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 116 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_RESTORE); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 117 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WRITEMEM); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 118 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LOADMEM); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 119 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SETPMEM); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 120 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEREF); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 121 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUERY); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 122 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PENDING); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TAKE); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DMA); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IRQ); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SMI); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 127 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_NMI); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TLB); }
	YY_BREAK
case 70:
#line 130 "bx_lexer.l"
case 71:
YY_RULE_SETUP
#line 130 "bx_lexer.l"
{ BEGIN(DISASM); bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISASM); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 131 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INSTRUMENT); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 132 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STOP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 133 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DOIT); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 134 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACE); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 135 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEREG); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 136 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEMEM); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 137 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SWITCH_MODE); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 138 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SIZE); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 139 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PTIME); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 140 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TIMEBP); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 141 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TIMEBP_ABSOLUTE); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 142 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_MODEBP); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 143 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_VMEXITBP); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 144 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT_STACK); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 145 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_BT); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 146 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WATCH); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 147 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_UNWATCH); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 148 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_READ); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 149 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WRITE); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 150 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_RUN_TO_LADDR); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 151 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SHOW); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 152 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LOAD_SYMBOLS); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 153 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SET_MAGIC_BREAK_POINTS); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 154 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CLEAR_MAGIC_BREAK_POINTS); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 155 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOLS); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 156 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LIST_SYMBOLS); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 157 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GLOBAL); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 158 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WHERE); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 159 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT_STRING); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 160 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PAGE); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 161 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEVICE); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 162 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ALL); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 163 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_AL; return(BX_TOKEN_8BL_REG);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 164 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_BL; return(BX_TOKEN_8BL_REG);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 165 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_CL; return(BX_TOKEN_8BL_REG);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 166 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_DL; return(BX_TOKEN_8BL_REG);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 167 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_SIL); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 168 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_DIL); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 169 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_SPL); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 170 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_BPL); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 171 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R8);  }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 172 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R9);  }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 173 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R10); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 174 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R11); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 175 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R12); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 176 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R13); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 177 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R14); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 178 "bx_lexer.l"
{ LONG_MODE_8BL_REG(BX_8BIT_REG_R15); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 179 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_AH; return(BX_TOKEN_8BH_REG);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 180 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_BH; return(BX_TOKEN_8BH_REG);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 181 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_CH; return(BX_TOKEN_8BH_REG);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 182 "bx_lexer.l"
{ bxlval.uval = BX_8BIT_REG_DH; return(BX_TOKEN_8BH_REG);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 183 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_AX; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 184 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_BX; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 185 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_CX; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 186 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_DX; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 187 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_SI; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 188 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_DI; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 189 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_BP; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 190 "bx_lexer.l"
{ bxlval.uval = BX_16BIT_REG_SP; return(BX_TOKEN_16B_REG);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 191 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R8);  }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 192 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R9);  }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 193 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R10); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 194 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R11); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 195 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R12); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 196 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R13); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 197 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R14); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 198 "bx_lexer.l"
{ LONG_MODE_16B_REG(BX_16BIT_REG_R15); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 199 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_EAX; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 200 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_EBX; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 201 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_ECX; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 202 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_EDX; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 203 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_ESI; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 204 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_EDI; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 205 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_EBP; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 206 "bx_lexer.l"
{ bxlval.uval = BX_32BIT_REG_ESP; return(BX_TOKEN_32B_REG);}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 207 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R8);  }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 208 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R9);  }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 209 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R10); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 210 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R11); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 211 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R12); }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 212 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R13); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 213 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R14); }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 214 "bx_lexer.l"
{ LONG_MODE_32B_REG(BX_32BIT_REG_R15); }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 215 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RAX); }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 216 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RBX); }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 217 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RCX); }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 218 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RDX); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 219 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RSI); }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 220 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RDI); }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 221 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RSP); }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 222 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_RBP); }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 223 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R8);  }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 224 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R9);  }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 225 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R10); }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 226 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R11); }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 227 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R12); }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 228 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R13); }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 229 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R14); }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 230 "bx_lexer.l"
{ LONG_MODE_64B_REG(BX_64BIT_REG_R15); }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 231 "bx_lexer.l"
{ return(BX_TOKEN_REG_IP); }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 232 "bx_lexer.l"
{ return(BX_TOKEN_REG_EIP);}
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 233 "bx_lexer.l"
{ return(BX_TOKEN_REG_RIP);}
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 234 "bx_lexer.l"
{ return(BX_TOKEN_REG_SSP);}
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 235 "bx_lexer.l"
{ bxlval.uval = BX_SEG_REG_CS; return(BX_TOKEN_CS); }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 236 "bx_lexer.l"
{ bxlval.uval = BX_SEG_REG_ES; return(BX_TOKEN_ES); }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 237 "bx_lexer.l"
{ bxlval.uval = BX_SEG_REG_SS; return(BX_TOKEN_SS); }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 238 "bx_lexer.l"
{ bxlval.uval = BX_SEG_REG_DS; return(BX_TOKEN_DS); }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 239 "bx_lexer.l"
{ bxlval.uval = BX_SEG_REG_FS; return(BX_TOKEN_FS); }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 240 "bx_lexer.l"
{ bxlval.uval = BX_SEG_REG_GS; return(BX_TOKEN_GS); }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 241 "bx_lexer.l"
{ EVEX_OPMASK_REG(bxtext[1] - '0'); }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 242 "bx_lexer.l"
{ bxlval.uval = 0; return (BX_TOKEN_FLAGS); }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 243 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_XML); }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 244 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_HELP); }
	YY_BREAK
case 186:
#line 246 "bx_lexer.l"
case 187:
YY_RULE_SETUP
#line 246 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CALC); }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 247 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ADDLYT); }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 248 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_REMLYT); }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 249 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LYT); }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 250 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SOURCE); }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 251 "bx_lexer.l"
{ BEGIN(INITIAL); bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 252 "bx_lexer.l"
{ BEGIN(INITIAL); bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 253 "bx_lexer.l"
{ BEGIN(INITIAL); bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISFORMAT); }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 254 "bx_lexer.l"
{ return ('+'); }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 255 "bx_lexer.l"
{ return ('-'); }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 256 "bx_lexer.l"
{ return (BX_TOKEN_DEREF_CHR); }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 257 "bx_lexer.l"
{ return ('*'); }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 258 "bx_lexer.l"
{ return ('/'); }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 259 "bx_lexer.l"
{ return (BX_TOKEN_RSHIFT); }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 260 "bx_lexer.l"
{ return (BX_TOKEN_LSHIFT); }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 261 "bx_lexer.l"
{ return (BX_TOKEN_EQ); }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 262 "bx_lexer.l"
{ return (BX_TOKEN_NE); }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 263 "bx_lexer.l"
{ return (BX_TOKEN_LE); }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 264 "bx_lexer.l"
{ return (BX_TOKEN_GE); }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 265 "bx_lexer.l"
{ return ('>'); }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 266 "bx_lexer.l"
{ return ('<'); }
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 267 "bx_lexer.l"
{ return ('&'); }
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 268 "bx_lexer.l"
{ return ('|'); }
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 269 "bx_lexer.l"
{ return ('^'); }
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 270 "bx_lexer.l"
{ return ('!'); }
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 271 "bx_lexer.l"
{ return ('@'); }
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 272 "bx_lexer.l"
{ return ('('); }
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 273 "bx_lexer.l"
{ return (')'); }
	YY_BREAK
case 215:
#line 275 "bx_lexer.l"
case 216:
YY_RULE_SETUP
#line 275 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext+1); bxlval.sval[strlen(bxlval.sval)-1] = 0; return(BX_TOKEN_STRING); }
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 276 "bx_lexer.l"
{ bxlval.uval = strtoull(bxtext, NULL, 16); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 277 "bx_lexer.l"
{ bxlval.uval = strtoull(bxtext, NULL, 8); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 278 "bx_lexer.l"
{ bxlval.uval = strtoull(bxtext, NULL, 10); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 279 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOLNAME); }
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 280 "bx_lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 281 "bx_lexer.l"
{ return ('\n'); }
	YY_BREAK
case 223:
/* rule 223 can match eol */
YY_RULE_SETUP
#line 282 "bx_lexer.l"
{ return ('\n'); }
	YY_BREAK
case 224:
YY_RULE_SETUP
#line 283 "bx_lexer.l"
; // eat up comments '//'
	YY_BREAK
case 225:
YY_RULE_SETUP
#line 284 "bx_lexer.l"
{ return(bxtext[0]); }
	YY_BREAK
case 226:
YY_RULE_SETUP
#line 285 "bx_lexer.l"
{ BEGIN(INITIAL); unput(*bxtext); }
	YY_BREAK
case 227:
YY_RULE_SETUP
#line 286 "bx_lexer.l"
ECHO;
	YY_BREAK
#line 2432 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(EXAMINE):
case YY_STATE_EOF(DISASM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 510 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 510 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 509);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 286 "bx_lexer.l"


  int
bx_yyinput(char *buf, int max_size)
{
  int len;

  if (lex_input_size == 0) {
    fprintf(stderr, "lex: no characters in string input buffer.\n");
    exit(1);
  }

  len = strlen(lex_input_ptr) + 1;
  if (len > max_size)
    len = max_size;

  memcpy(buf, lex_input_ptr, len);

  return(len);
}

  void
bx_add_lex_input(char *buf)
{
  lex_input_ptr  = buf;
  lex_input_size = strlen(buf);

  // Since we're parsing from strings, flush out
  // all current buffer state, so the next read
  // requests from yyinput

  bx_flush_buffer( YY_CURRENT_BUFFER );
}

#endif /* if BX_DEBUGGER */

