#define yy_create_buffer bx_create_buffer
#define yy_delete_buffer bx_delete_buffer
#define yy_scan_buffer bx_scan_buffer
#define yy_scan_string bx_scan_string
#define yy_scan_bytes bx_scan_bytes
#define yy_flex_debug bx_flex_debug
#define yy_init_buffer bx_init_buffer
#define yy_flush_buffer bx_flush_buffer
#define yy_load_buffer_state bx_load_buffer_state
#define yy_switch_to_buffer bx_switch_to_buffer
#define yyin bxin
#define yyleng bxleng
#define yylex bxlex
#define yyout bxout
#define yyrestart bxrestart
#define yytext bxtext
#define yywrap bxwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/volker/Archiv/bochs-cvs-rsync-20110222/bochs/bx_debug/lexer.c,v 1.5 2005-04-16 21:43:06 sshwarts Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 168
#define YY_END_OF_BUFFER 169
static yyconst short int yy_accept[455] =
    {   0,
        0,    0,    0,    0,    0,    0,  169,  166,    1,  164,
      153,  166,  165,  166,  150,  166,  154,  155,  146,  144,
      145,  147,  161,  161,  163,  166,  166,  139,  152,  166,
       21,    7,   45,  166,  166,  166,  166,  166,  166,  166,
       13,  166,   14,   50,   29,   11,  166,   61,  166,  166,
       51,  151,  167,    1,  167,  163,  167,    1,    0,  157,
        0,  165,  162,    0,  156,    0,  159,  161,  160,    0,
      149,  148,    0,  108,  104,  112,  109,  105,  122,    0,
      113,    0,  110,  106,    0,    0,   26,  130,  114,    0,
      111,  121,  107,    0,    0,  133,    0,  115,    0,    0,

        0,    0,    0,  131,    0,    0,    0,    0,    0,  134,
        0,    0,  135,    0,    0,    0,  124,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    4,    0,   22,    0,
        0,    0,    0,    0,    0,    0,    0,   76,    0,    0,
      120,    0,  123,  132,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    0,    0,   52,  141,  142,  143,  162,
      158,    0,   34,    0,   47,   46,    0,    0,    0,   33,
        6,    0,   44,    0,    0,    3,   57,    0,    0,  116,
      127,  117,  118,  126,  119,  129,  125,  128,    0,    0,
        0,    0,   32,   37,    0,    0,   35,    0,    0,   58,

       36,    0,   38,    0,    0,    0,    0,    0,    5,    0,
        0,    0,    0,   59,    0,    0,    0,    0,    0,    0,
        0,    0,   30,    0,   77,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   39,    0,    0,  103,    0,
        0,    0,    0,    0,    0,  140,    8,   27,    0,    0,
        0,    0,   70,    0,   49,    0,    0,    0,    0,  138,
       24,    0,    0,    0,    0,    0,    0,  100,   12,  102,
        0,    0,    0,    0,    0,    0,    0,    0,   48,   84,
        0,    0,    0,    0,    0,   87,    0,    0,   10,   66,
        0,    0,   56,    0,    0,    0,    0,    0,    0,    0,

       15,   20,    0,   28,    0,    0,   40,   62,    0,    0,
      136,    0,    0,    0,    0,   41,    0,    0,    0,    0,
        0,    0,    0,    0,   68,    0,   75,   54,    0,    0,
       67,    0,    0,   90,   65,    9,    0,    0,    0,    0,
        0,   82,   92,   85,    0,    0,   43,    0,    0,    0,
        0,    0,   91,    0,   19,    0,   69,   80,  101,   23,
        0,    0,    0,    0,    0,   78,    0,    0,    0,    0,
        0,    0,    0,    0,   17,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   55,   98,    0,    0,   25,    0,
       60,   53,   89,    0,    0,    0,    0,   83,    0,   86,

        0,    0,   42,    0,    0,    0,    0,   79,    0,    0,
       96,    0,    0,   71,    0,   99,    0,    0,    0,    0,
        0,    0,    0,    0,   31,    0,   72,    0,    0,    0,
        0,    0,   64,    0,    0,    0,    0,    0,   94,   63,
        0,  137,    0,   81,    0,   95,    0,   97,   88,   93,
        0,   73,   74,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   13,    1,   14,    1,   15,   16,   17,   18,
       17,   17,   17,   17,   17,   19,   19,    1,   20,   21,
        1,   22,   23,    1,   24,   24,   24,   24,   24,   24,
       25,   25,   25,   25,   25,   26,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
        1,   27,    1,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   25,    1,   54,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    1,    4,    5,    5,    1,    1,    5,    4,
        6,    6,    6,    4,    4,    7,    7,    7,    5,    5,
        7,    5,    7,    5,    5,    5,    7,    7,    7,    5,
        7,    7,    5,    1
    } ;

static yyconst short int yy_base[463] =
    {   0,
        0,    0,   53,   55,   57,   59,  541,  542,  538,  542,
      542,   58,    0,    0,  542,   55,  542,  542,  542,  542,
      542,  542,   70,   74,  542,  518,  516,  542,  542,   43,
       57,   68,   89,  112,  109,   66,  503,  121,  135,  493,
      501,   36,  145,  485,  499,  163,   72,  490,   85,   87,
      487,  542,  542,  528,  170,  542,  196,  527,  120,  542,
        0,    0,    0,   57,  542,    0,  201,  205,  542,    0,
      542,  542,  495,  542,  487,  542,  542,  488,  101,  491,
      542,  484,  542,  542,  481,  473,   33,  542,  542,  481,
      542,  111,  542,  490,  481,  542,  477,  542,  465,   96,

      464,   99,  471,   66,  476,  466,  482,  465,  461,  542,
      461,  465,  542,  467,  458,   34,  542,  460,  456,  457,
      454,  459,  470,  466,  110,  463,  542,  461,  450,  453,
      441,  461,  462,  117,  453,  136,  196,  460,  441,  445,
      542,  449,  542,  542,  147,  154,  447,  455,  437,  432,
      436,  451,  432,  445,  440,  542,  217,  221,  228,    0,
        0,  431,  542,  429,  542,  542,  445,  442,  425,  542,
      542,  436,  437,  435,  421,  438,  542,  419,  422,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  417,  416,
      427,  430,  542,  542,  430,  416,  542,  416,  410,  542,

      542,  423,  542,  407,  422,  420,  145,  405,  542,  418,
      417,  417,  431,  542,  395,  405,  410,  404,  398,  395,
      409,  398,  402,  405,  542,  212,  387,  390,  390,  391,
      390,  402,  400,  397,  398,  542,  399,  394,  542,  395,
      380,  377,  410,  375,  383,  542,  383,  373,  371,  404,
      364,  369,  542,  386,  542,  400,  366,  378,  381,  542,
      542,  364,  379,  356,  158,  376,  390,  542,  542,  542,
      375,  366,  363,  371,  353,  354,  365,  345,  542,  542,
      351,  349,  347,  362,  352,  542,  344,  343,  352,  542,
      346,  374,  542,  353,  338,  355,  347,  349,  348,  343,

      542,  542,  338,  542,  345,  337,  542,  330,  344,  340,
      542,  360,  333,  323,  332,  542,  323,  323,  324,  351,
      327,  323,  321,  333,  348,  331,  542,  542,  327,  311,
      542,  314,  323,  542,  542,  542,  316,  167,  341,  322,
      314,  542,  542,  542,  310,  302,  542,  316,  315,  304,
      304,  314,  542,  304,  542,  291,  542,  542,  542,  542,
      307,  306,  309,  293,  298,  542,  304,  288,  295,  288,
      290,  299,  159,  295,  542,  296,  296,  288,  287,  278,
      280,  288,  290,  282,  542,  542,  283,  273,  542,  274,
      542,  542,  542,  270,  277,  207,  283,  542,  273,  542,

      272,  283,  542,  262,  278,  269,  279,  542,  179,  262,
      542,  265,  272,  542,  270,  542,  259,  264,  273,  269,
      243,  247,  251,  234,  542,  219,  542,  240,  200,  218,
      205,  211,  542,  190,  190,  164,  151,  155,  542,  542,
      147,  542,  122,  542,   95,  542,  213,  542,  542,  542,
       72,  542,  542,  542,  256,  263,  270,  274,  281,  286,
      291,  296
    } ;

static yyconst short int yy_def[463] =
    {   0,
      454,    1,  455,  455,  455,  455,  454,  454,  454,  454,
      454,  456,  457,  458,  454,  459,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  460,  454,  454,  454,  456,  454,
      456,  457,  461,  459,  454,  459,  454,  454,  454,  462,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  460,  460,  454,  461,
      462,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,    0,  454,  454,  454,  454,  454,  454,
      454,  454
    } ;

static yyconst short int yy_nxt[597] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,    8,    8,    8,    8,   29,    8,   30,
       31,   32,   33,   34,   35,   36,   37,   38,    8,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,    8,   52,   54,   10,   54,   10,   54,   10,
       54,   10,   60,   65,  171,   65,  172,   55,  198,   55,
      126,   57,   56,   57,   56,   73,   56,  127,   56,   74,
      199,   66,   75,   66,   61,   67,   67,   67,   68,   68,
       68,   68,   68,   77,   76,   69,   78,   82,  111,   69,

       79,  147,   80,  187,   83,  112,  453,   84,   81,  188,
       85,   86,  113,   87,   88,  151,  153,  148,  149,   89,
      152,   70,   90,  154,   60,   91,   92,  207,   93,   94,
      450,   95,  155,  165,  166,   96,  184,   97,  106,  181,
       98,   99,  100,  101,  102,  174,   61,  182,  107,  103,
      185,  108,  109,  115,  216,  110,  175,  176,  104,  217,
      267,  208,  116,  105,  117,  120,  118,  121,  449,  219,
      119,  317,  122,  220,  128,  129,  229,  123,  130,  448,
      230,  131,  132,  268,  133,  157,  157,  157,  157,  231,
      134,  318,  135,  138,  232,  233,  139,  447,  371,  140,

      141,  396,  142,  446,  397,  445,  143,  372,  423,  144,
      145,  159,  159,  159,  159,  146,   67,   67,   67,   68,
       68,   68,   68,   68,  424,  221,   69,  222,  444,  443,
       69,  223,  157,  157,  157,  157,  454,  454,  454,  454,
      284,  413,  224,  159,  159,  159,  159,  451,  414,  442,
      441,  440,  439,  438,  452,  285,   53,   53,   53,   53,
       53,   53,   53,   59,  437,   59,   59,   59,   59,   59,
       62,  436,   62,   62,   62,   62,   62,   63,   63,   63,
       63,   64,  435,   64,   64,   64,   64,   64,  158,  434,
      433,  158,  158,  160,  160,  160,  160,  160,  161,  161,

      432,  161,  431,  430,  429,  428,  427,  426,  425,  422,
      421,  420,  419,  418,  417,  416,  415,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,

      325,  324,  323,  322,  321,  320,  319,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  228,  227,  226,  225,
      218,  215,  214,  213,  212,  211,  210,  209,  206,  205,

      204,  203,  202,  201,  200,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  186,  183,  180,  179,  178,  177,
      173,  170,  169,  168,  167,  164,  163,  162,   58,   58,
      156,  150,  137,  136,  125,  124,  114,   72,   71,   58,
      454,    7,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454

    } ;

static yyconst short int yy_chk[597] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    5,    5,
        6,    6,   12,   16,   87,   64,   87,    3,  116,    4,
       42,    5,    3,    6,    4,   30,    5,   42,    6,   30,
      116,   16,   30,   64,   12,   23,   23,   23,   23,   24,
       24,   24,   24,   31,   30,   23,   31,   32,   36,   24,

       31,   47,   31,  104,   32,   36,  451,   32,   31,  104,
       32,   32,   36,   32,   32,   49,   50,   47,   47,   32,
       49,   23,   33,   50,   59,   33,   33,  125,   33,   33,
      445,   33,   50,   79,   79,   33,  102,   33,   35,  100,
       33,   34,   34,   34,   34,   92,   59,  100,   35,   34,
      102,   35,   35,   38,  134,   35,   92,   92,   34,  134,
      207,  125,   38,   34,   38,   39,   38,   39,  443,  136,
       38,  265,   39,  136,   43,   43,  145,   39,   43,  441,
      145,   43,   43,  207,   43,   55,   55,   55,   55,  145,
       43,  265,   43,   46,  146,  146,   46,  438,  338,   46,

       46,  373,   46,  437,  373,  436,   46,  338,  409,   46,
       46,   57,   57,   57,   57,   46,   67,   67,   67,   67,
       68,   68,   68,   68,  409,  137,   67,  137,  435,  434,
       68,  137,  157,  157,  157,  157,  158,  158,  158,  158,
      226,  396,  137,  159,  159,  159,  159,  447,  396,  432,
      431,  430,  429,  428,  447,  226,  455,  455,  455,  455,
      455,  455,  455,  456,  426,  456,  456,  456,  456,  456,
      457,  424,  457,  457,  457,  457,  457,  458,  458,  458,
      458,  459,  423,  459,  459,  459,  459,  459,  460,  422,
      421,  460,  460,  461,  461,  461,  461,  461,  462,  462,

      420,  462,  419,  418,  417,  415,  413,  412,  410,  407,
      406,  405,  404,  402,  401,  399,  397,  395,  394,  390,
      388,  387,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  374,  372,  371,  370,  369,  368,  367,  365,  364,
      363,  362,  361,  356,  354,  352,  351,  350,  349,  348,
      346,  345,  341,  340,  339,  337,  333,  332,  330,  329,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      315,  314,  313,  312,  310,  309,  308,  306,  305,  303,
      300,  299,  298,  297,  296,  295,  294,  292,  291,  289,
      288,  287,  285,  284,  283,  282,  281,  278,  277,  276,

      275,  274,  273,  272,  271,  267,  266,  264,  263,  262,
      259,  258,  257,  256,  254,  252,  251,  250,  249,  248,
      247,  245,  244,  243,  242,  241,  240,  238,  237,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  213,  212,
      211,  210,  208,  206,  205,  204,  202,  199,  198,  196,
      195,  192,  191,  190,  189,  179,  178,  176,  175,  174,
      173,  172,  169,  168,  167,  164,  162,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  142,  140,  139,  138,
      135,  133,  132,  131,  130,  129,  128,  126,  124,  123,

      122,  121,  120,  119,  118,  115,  114,  112,  111,  109,
      108,  107,  106,  105,  103,  101,   99,   97,   95,   94,
       90,   86,   85,   82,   80,   78,   75,   73,   58,   54,
       51,   48,   45,   44,   41,   40,   37,   27,   26,    9,
        7,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
/////////////////////////////////////////////////////////////////////////
// $Id: lexer.c,v 1.5 2005-04-16 21:43:06 sshwarts Exp $
/////////////////////////////////////////////////////////////////////////

#include <stdlib.h>
#include <string.h>
#include "debug.h"
#if BX_DEBUGGER

#include "parser.h"


int bx_yyinput(char *buf, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf, ret, max_size) (ret = bx_yyinput(buf, max_size))

static char    *lex_input_ptr = NULL;
static unsigned lex_input_size = 0;
#define EXAMINE 1

#define DISASM 2


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "lexer.l"


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 455 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 542 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "lexer.l"
; // eat up whitespace
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SET); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIS); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ON); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_OFF); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CRC); }
	YY_BREAK
case 7:
#line 33 "lexer.l"
case 8:
YY_RULE_SETUP
#line 33 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTINUE); }
	YY_BREAK
case 9:
#line 35 "lexer.l"
case 10:
#line 36 "lexer.l"
case 11:
YY_RULE_SETUP
#line 36 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STEPN); }
	YY_BREAK
case 12:
#line 38 "lexer.l"
case 13:
#line 39 "lexer.l"
case 14:
YY_RULE_SETUP
#line 39 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STEP_OVER); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 40 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LIST_BREAK); }
	YY_BREAK
case 16:
#line 42 "lexer.l"
case 17:
YY_RULE_SETUP
#line 42 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_VBREAKPOINT); }
	YY_BREAK
case 18:
#line 44 "lexer.l"
case 19:
YY_RULE_SETUP
#line 44 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LBREAKPOINT); }
	YY_BREAK
case 20:
#line 46 "lexer.l"
case 21:
#line 47 "lexer.l"
case 22:
#line 48 "lexer.l"
case 23:
YY_RULE_SETUP
#line 48 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PBREAKPOINT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INFO); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PROGRAM); }
	YY_BREAK
case 26:
#line 52 "lexer.l"
case 27:
#line 53 "lexer.l"
case 28:
YY_RULE_SETUP
#line 53 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTROL_REGS); }
	YY_BREAK
case 29:
#line 55 "lexer.l"
case 30:
#line 56 "lexer.l"
case 31:
YY_RULE_SETUP
#line 56 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_REGISTERS); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FPU); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CPU); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ALL); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IDT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IVT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GDT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 63 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LDT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 64 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TSS); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIRTY); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 66 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LINUX); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DUMP_CPU); }
	YY_BREAK
case 43:
#line 69 "lexer.l"
case 44:
#line 70 "lexer.l"
case 45:
YY_RULE_SETUP
#line 70 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEL_BREAKPOINT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ENABLE_BREAKPOINT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISABLE_BREAKPOINT); }
	YY_BREAK
case 48:
#line 74 "lexer.l"
case 49:
#line 75 "lexer.l"
case 50:
YY_RULE_SETUP
#line 75 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUIT); }
	YY_BREAK
case 51:
#line 77 "lexer.l"
case 52:
YY_RULE_SETUP
#line 77 "lexer.l"
{ BEGIN(EXAMINE); bxlval.sval = strdup(bxtext); return(BX_TOKEN_EXAMINE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SETPMEM); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 79 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUERY); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 80 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PENDING); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 81 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TAKE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 82 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DMA); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 83 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IRQ); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 84 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PIC); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SET_CPU); }
	YY_BREAK
case 61:
#line 87 "lexer.l"
case 62:
#line 88 "lexer.l"
case 63:
YY_RULE_SETUP
#line 88 "lexer.l"
{ BEGIN(DISASM); bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISASSEMBLE); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 89 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INSTRUMENT); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 90 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_START); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 91 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STOP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 92 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_RESET); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 93 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 94 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LOADER); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 95 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DOIT); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 96 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEON); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 97 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEOFF); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 98 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEREGON); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 99 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEREGOFF); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 100 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PTIME); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 101 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TIMEBP); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 102 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TIMEBP_ABSOLUTE); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 103 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_RECORD); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 104 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PLAYBACK); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 105 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_MODEBP); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 106 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT_STACK); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 107 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WATCH); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 108 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_UNWATCH); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 109 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_READ); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 110 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WRITE); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 111 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTINUE); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 112 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SHOW); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 113 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOL); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 114 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOLS); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 115 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LIST_SYMBOLS); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 116 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GLOBAL); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 117 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WHERE); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 118 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT_STRING); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 119 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIFF_MEMORY); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 120 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYNC_MEMORY); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 121 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYNC_CPU); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 122 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FAST_FORWARD); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 123 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PHY_2_LOG); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 124 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INFO_ADDRESS); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 125 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_NE2000); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 126 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_NE2000); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 127 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PAGE); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 128 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_VGA); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 129 "lexer.l"
{ bxlval.reg=rAL; return (BX_TOKEN_REG_AL);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 130 "lexer.l"
{ bxlval.reg=rBL; return (BX_TOKEN_REG_BL);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 131 "lexer.l"
{ bxlval.reg=rCL; return (BX_TOKEN_REG_CL);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 132 "lexer.l"
{ bxlval.reg=rDL; return (BX_TOKEN_REG_DL);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 133 "lexer.l"
{ bxlval.reg=rAH; return (BX_TOKEN_REG_AH);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 134 "lexer.l"
{ bxlval.reg=rBH; return (BX_TOKEN_REG_BH);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 135 "lexer.l"
{ bxlval.reg=rCH; return (BX_TOKEN_REG_CH);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 136 "lexer.l"
{ bxlval.reg=rDH; return (BX_TOKEN_REG_DH);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 137 "lexer.l"
{ bxlval.reg=rAX; return (BX_TOKEN_REG_AX);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 138 "lexer.l"
{ bxlval.reg=rBX; return (BX_TOKEN_REG_BX);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 139 "lexer.l"
{ bxlval.reg=rCX; return (BX_TOKEN_REG_CX);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 140 "lexer.l"
{ bxlval.reg=rDX; return (BX_TOKEN_REG_DX);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 141 "lexer.l"
{ bxlval.reg=rEAX; return (BX_TOKEN_REG_EAX);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 142 "lexer.l"
{ bxlval.reg=rEBX; return (BX_TOKEN_REG_EBX);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 143 "lexer.l"
{ bxlval.reg=rECX; return (BX_TOKEN_REG_ECX);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 144 "lexer.l"
{ bxlval.reg=rEDX; return (BX_TOKEN_REG_EDX);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 145 "lexer.l"
{ bxlval.reg=rSI; return (BX_TOKEN_REG_SI);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 146 "lexer.l"
{ bxlval.reg=rDI; return (BX_TOKEN_REG_DI);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 147 "lexer.l"
{ bxlval.reg=rBP; return (BX_TOKEN_REG_BP);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 148 "lexer.l"
{ bxlval.reg=rSP; return (BX_TOKEN_REG_SP);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 149 "lexer.l"
{ bxlval.reg=rIP; return (BX_TOKEN_REG_IP);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 150 "lexer.l"
{ bxlval.reg=rESI; return (BX_TOKEN_REG_ESI);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 151 "lexer.l"
{ bxlval.reg=rEDI; return (BX_TOKEN_REG_EDI);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 152 "lexer.l"
{ bxlval.reg=rEBP; return (BX_TOKEN_REG_EBP);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 153 "lexer.l"
{ bxlval.reg=rESP; return (BX_TOKEN_REG_ESP);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 154 "lexer.l"
{ bxlval.reg=rEIP; return (BX_TOKEN_REG_EIP);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 155 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CS); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 156 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ES); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 157 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SS); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 158 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DS); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 159 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FS); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 160 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GS); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 161 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FLAGS); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 162 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ALWAYS_CHECK); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 163 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_HELP); }
	YY_BREAK
case 139:
#line 165 "lexer.l"
case 140:
YY_RULE_SETUP
#line 165 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CALC); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 166 "lexer.l"
{ BEGIN(INITIAL); bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 167 "lexer.l"
{ BEGIN(INITIAL); bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 168 "lexer.l"
{ BEGIN(INITIAL); bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISFORMAT); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return ('+'); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return ('-'); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return ('*'); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return ('/'); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return (BX_TOKEN_RSHIFT); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return (BX_TOKEN_LSHIFT); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return ('&'); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 176 "lexer.l"
{ return ('|'); }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 177 "lexer.l"
{ return ('^'); }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return ('!'); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return ('('); }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 180 "lexer.l"
{ return (')'); }
	YY_BREAK
case 156:
#line 182 "lexer.l"
case 157:
YY_RULE_SETUP
#line 182 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STRING); }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 183 "lexer.l"
{ bxlval.uval = strtoul(bxtext+2, NULL, 16); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 184 "lexer.l"
{ bxlval.uval = strtoul(bxtext+1, NULL, 8); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 185 "lexer.l"
{ bxlval.ulval = strtoull(bxtext, NULL, 10); return(BX_TOKEN_LONG_NUMERIC); }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 186 "lexer.l"
{ bxlval.uval = strtoul(bxtext, NULL, 10); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 187 "lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOLNAME); }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 188 "lexer.l"
{ return ('\n'); }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 189 "lexer.l"
{ return('\n'); }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 190 "lexer.l"
; // eat up comments '//'
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 191 "lexer.l"
{ return(bxtext[0]); }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 192 "lexer.l"
{ BEGIN(INITIAL); unput(*bxtext); }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 193 "lexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(EXAMINE):
case YY_STATE_EOF(DISASM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 455 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 455 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 454);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 193 "lexer.l"


// [A-Za-z_][A-Za-z0-9_]*   { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }

  int
bx_yyinput(char *buf, int max_size)
{
  int len;

  if (lex_input_size == 0) {
    fprintf(stderr, "lex: no characters in string input buffer.\n");
    exit(1);
  }

  len = strlen(lex_input_ptr) + 1;
  if (len > max_size)
    len = max_size;

  memcpy(buf, lex_input_ptr, len);

  return len;
}

  void
bx_add_lex_input(char *buf)
{
  lex_input_ptr  = buf;
  lex_input_size = strlen(buf);

  // Since we're parsing from strings, flush out
  // all current buffer state, so the next read
  // requests from yyinput

  bx_flush_buffer( YY_CURRENT_BUFFER );
}

#endif /* if BX_DEBUGGER */
