#!/bin/sh
#
# test-x11-fonts
# $Id: test-x11-fonts,v 1.1.4.1 2002-03-17 08:51:19 bdenney Exp $
#
# This script tries to run xterm using the vga font that bochs requires.  If
# xterm can't find the vga font, then certainly bochs will not be able to
# either.

echo In this test, I\'m going to try to create two xterms.  The first
echo will try the default font.  Hopefully there will be no errors in
echo this first test.  Press return to begin or control-C to abort.
read
echo Test 1...
xterm -e sh -c 'echo Testing default font; sleep 1'
echo ...done with Test 1.

echo Now I\'ll make an xterm with the vga font.  If the vga font is not
echo installed correctly, you will see errors in this test.  Press return
echo to begin.
read
echo Test 2...
xterm -fn vga -e sh -c 'echo Testing vga font; sleep 1'
echo ...done with Test 2.
echo
echo If you see any errors in test 2 that don\'t appear in test 1, then 
echo your vga font is not installed correctly.  Try running the
echo install-x11-fonts script, and/or reading the documentation at
echo 'http://bochs.sourceforge.net/docs-html/install.html#Setting up environment'
echo Any warnings or errors in the should be investigated.  Please report any 
echo bogus warnings to bochs-testing@tlw.com.
