#define yy_create_buffer bx_create_buffer
#define yy_delete_buffer bx_delete_buffer
#define yy_scan_buffer bx_scan_buffer
#define yy_scan_string bx_scan_string
#define yy_scan_bytes bx_scan_bytes
#define yy_flex_debug bx_flex_debug
#define yy_init_buffer bx_init_buffer
#define yy_flush_buffer bx_flush_buffer
#define yy_load_buffer_state bx_load_buffer_state
#define yy_switch_to_buffer bx_switch_to_buffer
#define yyin bxin
#define yyleng bxleng
#define yylex bxlex
#define yyout bxout
#define yyrestart bxrestart
#define yytext bxtext
#define yywrap bxwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/volker/Archiv/bochs-cvs-rsync-20110222/bochs/debug/lexer.c,v 1.12 2002-11-19 09:25:20 bdenney Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
static yyconst short int yy_accept[375] =
    {   0,
        0,    0,  117,  115,    1,  113,  115,  114,  115,  115,
      111,  111,  115,   20,    7,   39,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,   41,   25,   11,  115,
      115,  115,  115,   42,    1,    0,  104,  114,  112,  107,
      106,  109,  111,  110,    0,    0,    0,    0,    0,   22,
       95,    0,    0,    0,    0,   98,    0,   96,    0,    0,
        0,   99,    0,    0,  100,    0,    0,    0,    0,   14,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,
       16,    0,    0,    0,    0,    0,    0,    0,   70,    0,
        0,   10,   97,    0,    0,    0,    0,    0,    0,    0,

        0,   12,    0,    0,    0,   43,  112,  105,  108,   54,
       29,    0,    0,    6,    0,   38,    0,    0,    3,   57,
       48,    0,    0,    0,    0,   28,   31,    0,    0,   30,
        0,    0,   49,    0,   32,    0,    0,    0,    0,   56,
        0,    5,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   26,    0,   71,    2,    0,    0,
        0,    0,   55,    0,    0,    0,   33,    0,  102,    0,
        0,    0,    0,    0,    0,    0,   23,    0,    0,    0,
        0,   64,    0,    0,    0,    0,  103,   18,    0,    0,
        0,    0,    0,    0,    0,   92,   94,    0,    0,    0,

        0,    0,    0,    0,    0,   40,   78,    0,    0,    0,
        0,    0,   81,    0,    9,   60,    0,   47,    0,    0,
        0,    0,    0,    0,    0,   19,    0,   24,    0,    0,
       34,   51,    0,    0,    0,    0,    0,    0,   35,    0,
        0,   53,    0,    0,    0,    0,    0,    0,   62,    0,
       69,   45,    0,    0,   61,    0,    0,   59,    8,    0,
        0,    0,    0,   76,   84,   79,    0,    0,   37,    0,
        0,    0,    0,    0,   83,    0,   15,    0,   63,   74,
       93,   17,    0,    0,    0,    0,    0,   72,    0,    0,
        0,    0,    0,    0,    0,   13,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   46,   90,    0,    0,   21,
        0,   50,   44,    0,    0,    0,    0,   77,    0,   80,
        0,    0,   36,    0,    0,    0,    0,   73,    0,    0,
       88,    0,    0,   65,    0,   91,    0,    0,    0,    0,
        0,    0,    0,    0,   27,    0,   66,    0,    0,    0,
        0,    0,   58,    0,    0,    0,    0,    0,   86,   52,
        0,  101,    0,   75,    0,   87,    0,   89,   82,   85,
        0,   67,   68,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    1,    8,    9,   10,   11,
       10,   10,   10,   10,   10,   12,   12,    1,    1,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   13,   13,
       14,   14,   14,   14,   14,   15,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        1,    1,    1,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   14,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    4,    5,    5,    5,    4,    6,    6,    6,
        4,    4,    7,    7,    7,    5,    5,    5,    5,    7,
        5,    5,    5,    7,    7,    7,    5,    7,    7,    5
    } ;

static yyconst short int yy_base[382] =
    {   0,
        0,    0,  428,  429,  425,  429,  422,    0,    0,   32,
       36,   43,   29,  392,   27,   38,  390,   47,   42,  402,
       50,   62,   54,  401,   64,   77,  385,  399,   95,   72,
      390,   85,   85,  387,  415,  412,  429,    0,    0,  112,
        0,  127,  134,  429,    0,  395,  387,  392,  383,   46,
      429,  384,  118,  393,  384,  429,  380,  429,  373,  373,
      369,  429,  369,  373,  429,  375,  366,   51,  368,  366,
      363,  368,  379,  360,  374,  366,  381,  369,  429,  367,
      356,  359,  347,  369,  102,  360,   86,  131,  367,  348,
      352,  429,  429,  136,  363,  351,  353,  361,  343,  338,

      348,  341,  338,  351,  346,  429,    0,  429,    0,  337,
      429,  352,  333,  429,  344,  345,  343,  329,  346,  429,
      429,  327,  330,  325,  340,  429,  429,  340,  326,  429,
      326,  320,  429,  333,  429,  317,  332,  327,  329,  429,
       82,  429,  328,  327,  327,  335,  305,  315,  320,  314,
      308,  305,  319,  308,  312,  315,  429,   83,  297,  301,
      302,  301,  429,  312,  309,  310,  429,  311,  429,  306,
      307,  292,  289,  316,  296,  296,  286,  284,  311,  277,
      282,  429,  299,  307,  292,  295,  429,  429,  278,  293,
      270,  126,  274,  289,  297,  429,  429,  288,  279,  276,

      284,  266,  267,  278,  258,  429,  429,  264,  262,  260,
      275,  265,  429,  257,  266,  429,  283,  429,  268,  253,
      270,  262,  264,  263,  258,  429,  253,  429,  260,  252,
      429,  245,  259,  255,  269,  248,  238,  247,  429,  238,
      238,  429,  239,  260,  242,  238,  236,  248,  257,  246,
      429,  429,  242,  226,  429,  229,  238,  429,  429,   69,
      251,  238,  230,  429,  429,  429,  226,  218,  429,  232,
      231,  220,  220,  230,  429,  220,  429,  207,  429,  429,
      429,  429,  223,  222,  225,  209,  214,  429,  220,  204,
      211,  207,  216,   95,  212,  429,  213,  213,  205,  204,

      195,  197,  205,  207,  199,  429,  429,  200,  190,  429,
      191,  429,  429,  187,  194,  112,  200,  429,  190,  429,
      189,  200,  429,  179,  195,  186,  196,  429,  139,  179,
      429,  182,  189,  429,  187,  429,  176,  181,  190,  186,
      158,  162,  162,  149,  429,  138,  429,  163,  129,  147,
      131,  137,  429,  135,  135,  130,  118,   96,  429,  429,
       97,  429,   81,  429,   77,  429,  138,  429,  429,  429,
       28,  429,  429,  429,  172,  179,  183,  188,  193,  195,
      200
    } ;

static yyconst short int yy_def[382] =
    {   0,
      374,    1,  374,  374,  374,  374,  375,  376,  377,  378,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  375,  374,  376,  379,  378,
      380,  374,  374,  374,  381,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  379,  374,  381,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,    0,  374,  374,  374,  374,  374,  374,
      374
    } ;

static yyconst short int yy_nxt[470] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
       12,   12,    4,    4,    4,    4,   13,   14,   15,   16,
       17,   18,   19,   20,   21,    4,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,    4,
       40,   40,   40,   40,   42,   42,   42,   43,   46,  373,
       44,   43,   43,   43,   43,   47,   49,   44,   52,   50,
       51,   63,   53,   59,  114,   54,  115,   55,   64,   67,
       74,   56,  131,   57,   45,   65,   60,   61,   68,   70,
       62,   71,   69,   75,  132,   78,   72,  292,   97,   76,
      195,   73,   79,   80,   81,  101,  293,   82,  211,  370,

       83,  103,  102,   84,   98,   99,  151,  196,  104,   85,
      152,   86,   89,  212,  369,   90,  368,  105,   91,   92,
       40,   40,   40,   40,  316,  367,  148,  317,   93,   94,
       95,  149,  240,  333,   96,   42,   42,   42,   43,  117,
      334,   44,   43,   43,   43,   43,  241,  153,   44,  154,
      118,  119,  160,  155,  120,  343,  161,  366,  365,  371,
      364,  363,  362,  361,  156,  162,  372,  360,  359,  358,
      357,  344,   36,  356,   36,   36,   36,   36,   36,   38,
      355,   38,   38,   38,   38,   38,   39,   39,   39,   39,
       41,  354,  353,   41,   41,  107,  107,  107,  107,  107,

      108,  108,  109,  109,  352,  109,  351,  350,  349,  348,
      347,  346,  345,  342,  341,  340,  339,  338,  337,  336,
      335,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,

      249,  248,  247,  246,  245,  244,  243,  242,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  159,  158,  157,  150,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,

      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      116,  113,  112,  111,  110,   37,   35,  106,  100,   88,
       87,   77,   66,   58,   48,   37,   35,  374,    3,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374
    } ;

static yyconst short int yy_chk[470] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       10,   10,   10,   10,   11,   11,   11,   11,   13,  371,
       11,   12,   12,   12,   12,   13,   15,   12,   16,   15,
       15,   19,   16,   18,   50,   16,   50,   16,   19,   21,
       23,   16,   68,   16,   11,   19,   18,   18,   21,   22,
       18,   22,   21,   23,   68,   25,   22,  260,   30,   23,
      141,   22,   25,   26,   26,   32,  260,   26,  158,  365,

       26,   33,   32,   26,   30,   30,   87,  141,   33,   26,
       87,   26,   29,  158,  363,   29,  361,   33,   29,   29,
       40,   40,   40,   40,  294,  358,   85,  294,   29,   29,
       29,   85,  192,  316,   29,   42,   42,   42,   42,   53,
      316,   42,   43,   43,   43,   43,  192,   88,   43,   88,
       53,   53,   94,   88,   53,  329,   94,  357,  356,  367,
      355,  354,  352,  351,   88,   94,  367,  350,  349,  348,
      346,  329,  375,  344,  375,  375,  375,  375,  375,  376,
      343,  376,  376,  376,  376,  376,  377,  377,  377,  377,
      378,  342,  341,  378,  378,  379,  379,  379,  379,  379,

      380,  380,  381,  381,  340,  381,  339,  338,  337,  335,
      333,  332,  330,  327,  326,  325,  324,  322,  321,  319,
      317,  315,  314,  311,  309,  308,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  295,  293,  292,  291,  290,
      289,  287,  286,  285,  284,  283,  278,  276,  274,  273,
      272,  271,  270,  268,  267,  263,  262,  261,  257,  256,
      254,  253,  250,  249,  248,  247,  246,  245,  244,  243,
      241,  240,  238,  237,  236,  235,  234,  233,  232,  230,
      229,  227,  225,  224,  223,  222,  221,  220,  219,  217,
      215,  214,  212,  211,  210,  209,  208,  205,  204,  203,

      202,  201,  200,  199,  198,  195,  194,  193,  191,  190,
      189,  186,  185,  184,  183,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  168,  166,  165,
      164,  162,  161,  160,  159,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  139,
      138,  137,  136,  134,  132,  131,  129,  128,  125,  124,
      123,  122,  119,  118,  117,  116,  115,  113,  112,  110,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   91,   90,   89,   86,   84,   83,   82,   81,   80,
       78,   77,   76,   75,   74,   73,   72,   71,   70,   69,

       67,   66,   64,   63,   61,   60,   59,   57,   55,   54,
       52,   49,   48,   47,   46,   36,   35,   34,   31,   28,
       27,   24,   20,   17,   14,    7,    5,    3,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../debug/lexer.l"
#define INITIAL 0
#line 2 "../../debug/lexer.l"
/////////////////////////////////////////////////////////////////////////
// $Id: lexer.c,v 1.12 2002-11-19 09:25:20 bdenney Exp $
/////////////////////////////////////////////////////////////////////////

#include <stdlib.h>
#include <string.h>
#include "debug.h"
#if BX_DEBUGGER

#include "parser.h"


int bx_yyinput(char *buf, int max_size);
#undef YY_INPUT
#define YY_INPUT(buf, ret, max_size) (ret = bx_yyinput(buf, max_size))

static char    *lex_input_ptr = NULL;
static unsigned lex_input_size = 0;

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 23 "../../debug/lexer.l"


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 375 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 429 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "../../debug/lexer.l"
; // eat up whitespace
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SET); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIS); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ON); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_OFF); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CRC); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTINUE); }
	YY_BREAK
case 8:
#line 32 "../../debug/lexer.l"
case 9:
#line 33 "../../debug/lexer.l"
case 10:
#line 34 "../../debug/lexer.l"
case 11:
YY_RULE_SETUP
#line 34 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STEPN); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_VBREAKPOINT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_VBREAKPOINT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LBREAKPOINT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LBREAKPOINT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PBREAKPOINT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PBREAKPOINT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INFO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PBREAKPOINT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PBREAKPOINT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PROGRAM); }
	YY_BREAK
case 22:
#line 46 "../../debug/lexer.l"
case 23:
#line 47 "../../debug/lexer.l"
case 24:
YY_RULE_SETUP
#line 47 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTROL_REGS); }
	YY_BREAK
case 25:
#line 49 "../../debug/lexer.l"
case 26:
#line 50 "../../debug/lexer.l"
case 27:
YY_RULE_SETUP
#line 50 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_REGISTERS); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FPU); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ALL); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IDT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GDT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LDT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TSS); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIRTY); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LINUX); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DUMP_CPU); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEL_BREAKPOINT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEL_BREAKPOINT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DEL_BREAKPOINT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUIT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUIT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_EXAMINE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_EXAMINE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SETPMEM); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_QUERY); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PENDING); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TAKE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DMA); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_IRQ); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SET_CPU); }
	YY_BREAK
case 51:
#line 75 "../../debug/lexer.l"
case 52:
YY_RULE_SETUP
#line 75 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DISASSEMBLE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_MATHS); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ADD); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SUB); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_MUL); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIV); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INSTRUMENT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_START); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STOP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_RESET); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_LOADER); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DOIT); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEON); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEOFF); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEREGON); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TRACEREGOFF); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PTIME); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TIMEBP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_TIMEBP_ABSOLUTE); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_RECORD); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PLAYBACK); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_MODEBP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT_STACK); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WATCH); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_UNWATCH); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_READ); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WRITE); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CONTINUE); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SHOW); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOL); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GLOBAL); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_WHERE); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PRINT_STRING); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DIFF_MEMORY); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYNC_MEMORY); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYNC_CPU); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FAST_FORWARD); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 113 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PHY_2_LOG); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_INFO_ADDRESS); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_NE2000); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 116 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_NE2000); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 117 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_PAGE); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 118 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_CS); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 119 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ES); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 120 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SS); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 121 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_DS); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 122 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_FS); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 123 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_GS); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 124 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_ALWAYS_CHECK); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 125 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_V2L); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 126 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_HELP); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 127 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_STRING); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 128 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 129 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 130 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_XFORMAT); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 131 "../../debug/lexer.l"
{ bxlval.uval = strtoul(bxtext+2, NULL, 16); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 132 "../../debug/lexer.l"
{ bxlval.uval = strtoul(bxtext+1, NULL, 8); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 133 "../../debug/lexer.l"
{ bxlval.ulval = strtoull(bxtext, NULL, 10); return(BX_TOKEN_LONG_NUMERIC); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 134 "../../debug/lexer.l"
{ bxlval.uval = strtoul(bxtext, NULL, 10); return(BX_TOKEN_NUMERIC); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 135 "../../debug/lexer.l"
{ bxlval.sval = strdup(bxtext); return(BX_TOKEN_SYMBOLNAME); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 136 "../../debug/lexer.l"
{ return('\n'); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 137 "../../debug/lexer.l"
; // eat up comments '//'
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 138 "../../debug/lexer.l"
{ return(bxtext[0]); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 139 "../../debug/lexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 375 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 375 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 374);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 139 "../../debug/lexer.l"


// [A-Za-z_][A-Za-z0-9_]*   { bxlval.sval = strdup(bxtext); return(BX_TOKEN_GENERIC); }

  int
bx_yyinput(char *buf, int max_size)
{
  int len;

  if (lex_input_size == 0) {
    fprintf(stderr, "lex: no characters in string input buffer.\n");
    exit(1);
    }

  len = strlen(lex_input_ptr);
  if (len > max_size)
    max_size = len;

  memcpy(buf, lex_input_ptr, max_size);
  lex_input_size -= max_size;

  return(max_size);
}


  void
bx_add_lex_input(char *buf)
{
  lex_input_ptr  = buf;
  lex_input_size = strlen(buf);

  // Since we're parsing from strings, flush out
  // all current buffer state, so the next read
  // requests from yyinput

  bx_flush_buffer( YY_CURRENT_BUFFER );
}

#endif /* if BX_DEBUGGER */
