.\"Document Author:  Christophe Bothamy   -   cbothamy@free.fr"
.TH bximage 1 "29 Dec 2005" "bximage" "The Bochs Project"
.\"SKIP_SECTION"
.SH NAME
bxcommit \- Interactive Tool to Commit Redologs into flat Disk Images for Bochs
.\"SKIP_SECTION"
.SH USAGE
.B bxcommit
.\"SKIP_SECTION"
.SH DESCRIPTION
.LP
Bxcommit is an easy to use console based tool for committing
redologs into flat
disk  images, particularly  for  use with  Bochs.  It  is
completely interactive, so no command line arguments  are
needed to use bxcommit.
.\"SKIP_SECTION"
.SH LICENSE
This program  is distributed  under the terms of the  GNU
Lesser General Public License as published  by  the  Free
Software  Foundation.  See  the  COPYING file located  in
/usr/local/share/doc/bochs/ for details on the license and
the lack of warranty.
.\"SKIP_SECTION"
.SH AVAILABILITY
The latest version of this program can be found at:
  http://bochs.sourceforge.net/getcurrent.html
.\"SKIP_SECTION"
.SH SEE ALSO
bochs(1), bochsrc(5), bochs-dlx(1), bximage(1)
.PP
.nf
The Bochs IA-32 Emulator site on the World Wide Web:
  http://bochs.sourceforge.net

Online Bochs Documentation
	http://bochs.sourceforge.net/doc/docbook
.fi
.\"SKIP_SECTION"
.SH AUTHORS
Bximage  was written  by Christophe Bothamy,
based on Bochs bximage tool source code.
.\"SKIP_SECTION"
.SH BUGS
Please  report all  bugs to the bug tracker  on  our  web
site. Just go to http://bochs.sourceforge.net, and click
"Bug Reports" on the sidebar under "Feedback."
.PP
Provide a detailed description of the bug, the version of
the program you are running, the operating system you are
running the program on  and  the  operating   system  you
are running in the emulator.

