.\Document Author:  Timothy R. Butler   -   tbutler@uninetsolutions.com
.TH bochs 1 "The Bochs Project         bximage 1.0          2 Jun 2001"
.\"SKIP_SECTION"
.SH NAME
bximage \- Interactive Disk Image Creator for Bochs
.\"SKIP_SECTION"
.SH USAGE
.B bximage

.B bochsrc(1).
.\"SKIP_SECTION"
.SH DESCRIPTION
.LP
Bximage is an easy to use console based tool for creating
disk  images, particularly  for  use with  Bochs . It  is
completely interactive, so no command line arguments  are
needed to use bximage.
.\"SKIP_SECTION"
.SH LICENSE
This program  is distributed  under the terms of the  GNU
Lesser General Public License as published  by  the  Free
Software  Foundation.  See  the  COPYING file located  in
/usr/local/bochs/@VERSION@/ for details on the license and
the lack of warrantee.
.\"SKIP_SECTION"
.SH AVAILABILITY
The latest version of this program can be found at:
        http://bochs.sourceforge.net/getcurrent.html
.\"SKIP_SECTION"
.SH SEE ALSO
bochs(1), bochsrc(1), bochs-dlx(1)
.PP
.nf
The Bochs IA-32 Emulator site on the World Wide Web:
        http://bochs.sourceforge.net
.fi
.\"SKIP_SECTION"
.SH AUTHORS
The   Bochs  emulator  was   created   by  Kevin   Lawton
(kevin@mandrakesoft.com),  and  is  currently  maintained
by the  members of  the  Bochs x86 Emulator Project . You
can see a current roster of members at:
            http://bochs.sourceforge.net/getinvolved.html
.\"SKIP_SECTION"
.SH BUGS
Please  report all  bugs to the bug tracker  on  our  web
site. Just go to http://bochs.sourceforge.net , and click
"Bug Reports" on the sidebar under "Features."
.PP
Provide a detailed description of the bug, the version of
the program you are running, the operating system you are
running the program on  and  the  operating   system  you
are running in the emulator.

